title: Tee Picks Blog
description: Visual, SEO-friendly affiliate t-shirt roundups.
url: "https://pbgear.github.io"
baseurl: "/findthatshirt"
lang: en-US
timezone: America/New_York

markdown: kramdown
permalink: /:slug/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: /assets/images/placeholder-hero.svg

exclude:
  - README.md
